version: "3.8"

services:
    questdb:
        image: questdb/questdb:6.5.3
        container_name: questdb
        networks: 
            - "iotstack"
        ports:
            - "9000:9000" # REST API and Web Console
            - "9003:9003" # Min health server https://questdb.io/docs/reference/configuration/#minimal-http-server
        expose: 
            - 9009 # Don't Publish Influx Line Protocol Port 
        volumes: 
            - questdb_data:/root/.questdb/db
    
    telegraf:
        image: telegraf:1.24.2-alpine
        container_name: telegraf
        env_file: prototype.env
        restart: on-failure # required till user credentials created
        links: 
            - questdb
        depends_on: 
            # do not start before QuestDB
            - questdb
        networks: 
            - "iotstack"
        volumes: 
            - ./telegraf/telegraf.toml:/etc/telegraf/telegraf.conf:ro

volumes: 
    questdb_data:

networks:
    iotstack:
        external: true